name: CI

on:
    push:
        branches: [master]
    pull_request:
        types: [opened, synchronize]

env:
    NODE_VERSION: 22

permissions:
    contents: read

defaults:
    run:
        shell: bash

jobs:
    install:
        name: Checkout and Install
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v6
            -   name: Install
                uses: ./.github/actions/install
                with:
                    node-version: ${{ env.NODE_VERSION }}

    build:
        name: Build Packages
        needs: [install]
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v6
            -   name: Install
                uses: ./.github/actions/install
                with:
                    node-version: ${{ env.NODE_VERSION }}
            -   name: Build
                uses: ./.github/actions/build

    tests:
        name: Test Packages
        needs: [build]
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v6
            -   name: Install
                uses: ./.github/actions/install
                with:
                    node-version: ${{ env.NODE_VERSION }}
            -   name: Build
                uses: ./.github/actions/build
            -   name: Run tests
                run: npm test
