name: Merge

on:
    pull_request:
        branches:
            - master

env:
    NODE_VERSION: 22

defaults:
    run:
        shell: bash

jobs:
    merge:
        runs-on: ubuntu-latest

        permissions:
            pull-requests: write
            contents: write

        steps:
            -   name: Checkout
                uses: actions/checkout@v6

            -   uses: fastify/github-action-merge-dependabot@v3
